### ISSUE TITLE
Insufficient contrast between links and text

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.org#155]
Links lack sufficient contrast from text. Can you find the two links in this screenshot?

![Screenshot 2024-01-05 at 10 23 25 AM](https://github.com/plone/plone.org/assets/102112/325eecde-8429-4cdd-8639-6a3261206d0d)

```css
body {
    color: #595959;
}
a {
    color: #005b85;
}
```

Documentation uses colors that have been thoroughly analyzed by PyData and Sphinx Book Theme developers.

![Screenshot 2024-01-05 at 10 26 58 AM](https://github.com/plone/plone.org/assets/102112/4da11ea6-a6f8-4384-bbe9-fd03d41651d0)

```css
p {
  color: #333333;
}
a {
  color: #0071bc;
}
```

Can you please increase the contrast by darkening text and lightening links?
